IntelLabs/coach

- install.sh
Link step fails if continuing installation after interruption, requiring manual deletion of the link. Adding a force flag overrides the existing symbolic link from attempted installation in the newly created virtual environment.
> Add force flag to library symbolic link

- architectures/tensorflow_components/architecture.py
Apparently tensorflow still collects summary data even when no summary FileWriter is defined over the summaries. This is slowing down execution by 5-10x even when tensorboard visualization is off.
> fix for tensorboard visualization slowing execution even when it is off

- agents/actor_critic_agent.py
- agents/agent.py
- agents/bc_agent.py
- agents/clipped_ppo_agent.py
- agents/ddpg_agent.py
- agents/dfp_agent.py
- agents/imitation_agent.py
- agents/n_step_q_agent.py
- agents/naf_agent.py
- agents/nec_agent.py
- agents/policy_gradients_agent.py
- agents/ppo_agent.py
- agents/qr_dqn_agent.py
- agents/value_optimization_agent.py
- architectures/tensorflow_components/architecture.py
- architectures/tensorflow_components/general_network.py
- architectures/tensorflow_components/heads.py
- coach.py
- configurations.py
- environments/carla_environment_wrapper.py
- environments/doom_environment_wrapper.py
- environments/environment_wrapper.py
- environments/gym_environment_wrapper.py
- logger.py
- run_test.py
- utils.py
- many places in agents which previously work with observations now work with states
- `input_types` now defined as dictionary: `{'name': InputType}`
- `Agent.inputs` now defined as dictionary: `{'name': tf.placeholder}`
- functions which used to accept an input list whose order needed to match the order of `inputs_types` followed by the correct order of inputs added by a specific order of output heads, now accepts a dictionary: `{'name': np.array}`. these functions include: `train_and_sync_networks`, `predict` and `accumulate_gradients`.
Next steps not in this pull request include:
- output_types as dictionary: `{'name': OutputType}`. this will fix awkward names currently used such as: `output_0_0`
- environment observation space defined using `gym.Spaces`
NOTE: `CartPole_NEC` test is …
> Measurements as observation

- rl_coach/architectures/embedder_parameters.py
- rl_coach/architectures/head_parameters.py
- rl_coach/architectures/middleware_parameters.py
- rl_coach/architectures/tensorflow_components/general_network.py
I modified the following classes:
* HeadParameters
* MiddlewareParameters
* InputEmbedderParameters
Adding a `path` property (or function as I mention in challenges).
Then I modified:
* `GeneralTensorFlowNetwork.get_input_embedder`
* `GeneralTensorFlowNetwork.get_middleware`
* `GeneralTensorFlowNetwork.get_output_head`
To use these paths instead of their own local's.
I moved a local dictionary inside `GeneralTensorFlowNetwork.get_input_embedder` called mod_names to `embedder_parameters.MOD_NAMES` so that it's more accessible.
* `InputEmbedderParameters.path` can not be a property like the rest. You can call it with `emb_type` and the path will be created. But that's different than how most path's are made.
I ran pytest locally and do not see any dramatic changes in the number of passing …
> Now able to use and create custom tensorflow heads, embedders, and middleware.

- rl_coach/exploration_policies/additive_noise.py
- rl_coach/exploration_policies/truncated_normal.py
During heatup we may want to add agent-generated-noise (i.e. not "simple" random noise).
This is enabled by setting 'heatup_using_network_decisions' to True.  For example:
agent_params = DDPGAgentParameters()
agent_params.algorithm.heatup_using_network_decisions = True
The fix ensures that the correct noise is added not just while in the TRAINING phase, but
also during the HEATUP phase.
No one has enabled 'heatup_using_network_decisions' yet, which explains why this problem
arose only now (in my configuration I do enable 'heatup_using_network_decisions').
> Bug fix: when enabling 'heatup_using_network_decisions', we should add the correct noise

- rl_coach/tests/test_golden.py
- rl_coach/utils.py
When running golden tests through pytest, errors have been ignored. This pull request fixes that.
> Fix golden tests

- rl_coach/agents/bootstrapped_dqn_agent.py
- rl_coach/agents/categorical_dqn_agent.py
- rl_coach/agents/clipped_ppo_agent.py
- rl_coach/agents/ddqn_agent.py
- rl_coach/agents/dfp_agent.py
- rl_coach/agents/dqn_agent.py
- rl_coach/agents/mmc_agent.py
- rl_coach/agents/nec_agent.py
- rl_coach/agents/pal_agent.py
- rl_coach/agents/qr_dqn_agent.py
- rl_coach/agents/rainbow_dqn_agent.py
- rl_coach/agents/value_optimization_agent.py
- rl_coach/architectures/tensorflow_components/heads/__init__.py
- rl_coach/architectures/tensorflow_components/heads/categorical_q_head.py
- rl_coach/architectures/tensorflow_components/heads/dnd_q_head.py
- rl_coach/architectures/tensorflow_components/heads/dueling_q_head.py
- rl_coach/architectures/tensorflow_components/heads/q_head.py
- rl_coach/architectures/tensorflow_components/heads/quantile_regression_q_head.py
- rl_coach/architectures/tensorflow_components/heads/rainbow_q_head.py
- rl_coach/graph_managers/batch_rl_graph_manager.py
- rl_coach/memories/episodic/episodic_experience_replay.py
- rl_coach/memories/non_episodic/experience_replay.py
- rl_coach/off_policy_evaluators/ope_manager.py
- rl_coach/presets/CartPole_QR_DQN.py
allowing for the last training batch drawn to be smaller than batch_size + adding support for more agents in BatchRL by adding softmax with temperature to the corresponding heads + adding a CartPole_QR_DQN preset with a golden test + cleanups
The list of supported agents in BatchRL is now extended to - 
DQN
DDQN
Dueling DDQN
Categorical DQN (C51)
Rainbow DQN
QR DQN
Bootstrapped DQN
NEC
MMC
PAL
> Enabling-more-agents-for-Batch-RL-and-cleanup

- rl_coach/architectures/tensorflow_components/savers.py
- rl_coach/tests/test_global_variable_saver.py
This is a first step towards allowing serialization/deserialization to arrays and strings. This will allow us to send policy weights across the network without sending them to disk first. It will also give us an easier interface to use when we want to modify policy weights using evolutionary update steps.
I didn't change any of the logic around replacing `global/` names with `local/`, but when i tested this pattern, I realize the existing code already has a problem. If there are any `global/` variable name when restoring saved state, the code will attempt to load those global variables, and they won't exist in the same state. I am not sure how this currently working in master. This code doesn't modify any of that logic however.
> Allow serializing from/to arrays/str from GlobalVariableSaver

- rl_coach/environments/gym_environment.py
Removing code which was once required with older gym versions. Images are now rendered correctly by default with the latest gym.
> fix for fetch rendering 

- rl_coach/graph_managers/graph_manager.py
Following PR #191, checkpoint restore from a specific file (instead of a directory) is broken. This PR fixes that.
> Checkpoint restore from file bug-fix 

- rl_coach/agents/agent.py
- rl_coach/agents/ddqn_bcq_agent.py
- rl_coach/agents/value_optimization_agent.py
- rl_coach/graph_managers/batch_rl_graph_manager.py
- rl_coach/memories/episodic/episodic_experience_replay.py
- rl_coach/memories/non_episodic/experience_replay.py
- rl_coach/off_policy_evaluators/rl/sequential_doubly_robust.py
- rl_coach/off_policy_evaluators/rl/weighted_importance_sampling.py
Several bug fixes for Sequential Doubly Robust and Weighted Importance Sampling. Also rename of `get_shuffled_data_generator` -> `get_shuffled_training_data_generator`.
Sequential DR had the order of transitions in each episode backwards. Weighted Importance Sampling had some corner cases to be covered.
> bug fixes for OPE

- rl_coach/base_parameters.py
- rl_coach/presets/CartPole_DQN_BatchRL_BCQ.py
- rl_coach/tests/test_golden.py
Relaxing CartPole_DQN_BatchRL_BCQ number of read csv attempts by golden testing, as it is failing due to taking too long to create the initial csv (as a result of a dataset creation using a training agent)
> Preset dependent number of csv read attempts in golden testing

- rl_coach/tests/utils/args_utils.py
- rl_coach/tests/utils/definitions.py
- fixed cp parameter test 
- changing params test order, due to xfail tests which keeps the logs and not remove them. 
- added assert for query indexes
> tests: added assert for cp param and changing test args order

- .circleci/config.yml
* changing nightly workflow to the following:
- build all env
- run integration and unit tests
- run functional tests
- run doom_functional_tests
- run mujoco_function_tests
- run gym_functional_tests
- run golden gym
- run golden_doom
- run golden_mujoco
* removed Starcraft from functional_tests
* increase timeout on functional tests
* nightly running from Sunday-Friday
* weekly running on Saturday
> ci: using serial jobs in nightly

- .circleci/config.yml
- rl_coach/tests/test_coach_args.py
Fix/workaround to the OSError exception in CircleCI:
1. Increasing memory limitation on the functional test runs from 4GB to 8GB
2. If still fails - skipping the tests failing due to OSError bad address
> Workaround the OSError due to bad address failure on the CI runs

- .circleci/config.yml
uses new eks cluster (newer k8s version, M2.5 instead of T2.3 instances)
> update to point at new CI cluster.

- rl_coach/utilities/shared_running_stats.py
Numpy shared running stats didn't work if the objects weren't 1D vector or not type float32/float64.
> Fix numpy shared running stats

- rl_coach/environments/gym_environment.py
Atari environments are causing a stack overflow because of infinite recursion. This happens usually in advanced stages of the training when there are long episodes that reach the maximum step limit in gym.
This was likely introduced in PR #325 due to gym api change.
> Fix atari stack overflow

- rl_coach/graph_managers/batch_rl_graph_manager.py
Removing this assertion as it unjustifiably fails when using the agent for plain inference (where there's no dataset to train from, and also no environment to train against).
> Removing assertion from BatchRL GraphManager

- rl_coach/filters/action/box_discretization.py
- rl_coach/presets/Mujoco_Wolpertinger.py
Numpy 1.18 fails to cast scientific notation to int in the Wolpertinger preset causing CI failure.
> Wolpertinger preset failure fix

- requirements.txt
- rl_coach/data_stores/s3_data_store.py
They removed the `ResponseError` class
Limit version for now to avoid crashes (in CI as well)
> Fix breaking change from minio update

- .circleci/config.yml
The Python Kubernetes client depends on the `cryptography` package, which apparently requires the Rust compiler, and it currently fails building with the message below (see also [here](https://cryptography.io/en/latest/faq.html#installing-cryptography-fails-with-error-can-not-find-rust-compiler)).
Trying the suggested step 1 first.
```
running build_rust
=============================DEBUG ASSISTANCE=============================
If you are seeing a compilation error please try the following steps to
successfully install cryptography:
1) Upgrade to the latest pip and try again. This will fix errors for most
users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2) Read https://cryptography.io/en/latest/installation.html for specific
instructions for your platform.
3) Check our …
```
> Fix Rust compiler build error (Kubernetes dependency)
