install.sh

Trying to get this installed automatically (in a Dockerfile) outside of a corporate environment (so no proxy required).
This resolves #5 and #6

Fixes installer issues #5 and #6

---

agents/agent.py
architectures/architecture.py
architectures/neon_components/embedders.py
architectures/neon_components/heads.py
architectures/neon_components/middleware.py
architectures/network_wrapper.py
architectures/tensorflow_components/embedders.py
architectures/tensorflow_components/heads.py
architectures/tensorflow_components/middleware.py
configurations.py
environments/environment_wrapper.py
exploration_policies/exploration_policy.py
logger.py
memories/differentiable_neural_dictionary.py
memories/memory.py
utils.py

Unify base class using new-style (object).

---

agents/qr_dqn_agent.py
architectures/tensorflow_components/heads.py
presets.py

Code changes following issues #28 and #29 .
The new code was verified to be working for Doom, CartPole and Breakout.

QR-DQN bug fix and imporvements

---

agents/actor_critic_agent.py
agents/agent.py
agents/nec_agent.py
agents/value_optimization_agent.py
architectures/neon_components/general_network.py
architectures/network_wrapper.py
architectures/tensorflow_components/architecture.py
architectures/tensorflow_components/general_network.py
architectures/tensorflow_components/heads.py
install.sh
presets.py
utils.py

This is similar to the `lstm` branch/pr #37.  However, it has been tested against NEC agent.  I believe there is work in addition to the work in that branch to make LSTM work with `ValueOptimization` and `NEC` agents.

update nec and value optimization agents to work with recurrent middleware

---

agents/agent.py
agents/ddpg_agent.py
agents/policy_optimization_agent.py
agents/ppo_agent.py
agents/value_optimization_agent.py

fixed the LSTM middleware following issue #26

fixed the LSTM middleware initialization

---

agents/agent.py
architectures/tensorflow_components/architecture.py
architectures/tensorflow_components/embedders.py
architectures/tensorflow_components/general_network.py
architectures/tensorflow_components/heads.py
architectures/tensorflow_components/middleware.py
coach.py
configurations.py
parallel_actor.py
run_test.py

Basic functionality in place for dumping networks graphs, training loss and weights histograms.

adding support in tensorboard 

---

agents/actor_critic_agent.py
agents/agent.py
agents/n_step_q_agent.py
agents/policy_gradients_agent.py
configurations.py
logger.py

appending csv's from logger instead of rewriting them

---

rl_coach/graph_managers/graph_manager.py

remove unused variable losses

---

docs_raw/README.md

Update docs_raw README.md

---

rl_coach/memories/memory.py

Fixing the following error:
```
File "/Users/ryapeach/Documents/Workspace/coach/rl_coach/agents/agent.py", line 480, in update_log
self.agent_logger.create_signal_value('ER #Transitions', self.call_memory('num_transitions'))
File "/Users/ryapeach/Documents/Workspace/coach/rl_coach/agents/agent.py", line 423, in call_memory
result = getattr(self.memory, func)(*args)
AttributeError: <my memory class> object has no attribute 'num_transitions'
```
Added num_transitions to Memory interface.

Added num_transitions to Memory interface.

---

rl_coach/architectures/network_wrapper.py

Minor fix to remove warning issues when mxnet or tensorflow is not installed.

Fix warning on import tensorflow or mxnet

---

rl_coach/agents/agent.py
rl_coach/agents/clipped_ppo_agent.py
rl_coach/filters/filter.py
rl_coach/utilities/shared_running_stats.py

Do not update internal filter state when evaluating + fix SharedRunningStats checkpoint filenames + fix for finding the right checkpoint to restore.
Fixes issue #145.

Fix Issue #145

---

.circleci/config.yml

Add nightly running of golden and trace tests.

---

.circleci/config.yml

Also bump integration test timeout

ensure nightly test env containers exist.

---

requirements.txt
rl_coach/dashboard_components/experiment_board.py
rl_coach/dashboard_components/globals.py
rl_coach/dashboard_components/signals_file_base.py
setup.py

Replacing wxPython with Python's Tkinter.
1. Shortening installation time
2. Removing a 3rd party dependency that may cause failure
Fixes the following open issues:
Issue #192 
Issue #100 
Issue #185 
PR #165 may become redundant as a result of this change.

wxPython removal

---

.circleci/config.yml

Should reduce resource requirements and potential CPU contention but increases
overall execution time.

run nightly golden tests sequentially.

---

requirements.txt
rl_coach/coach.py
rl_coach/tests/README.md
rl_coach/tests/conftest.py
rl_coach/tests/test_args.py
rl_coach/tests/utils/args_utils.py
rl_coach/tests/utils/definitions.py
rl_coach/tests/utils/presets_utils.py
rl_coach/tests/utils/test_utils.py

* add utils for future tests.
* this is the first commit - I'll upload the test in separate test

tests: added new setup configuration

---

rl_coach/architectures/tensorflow_components/architecture.py
rl_coach/architectures/tensorflow_components/general_network.py
rl_coach/architectures/tensorflow_components/heads/acer_policy_head.py
rl_coach/architectures/tensorflow_components/heads/policy_head.py
rl_coach/architectures/tensorflow_components/heads/ppo_head.py

bug-fix for l2_regularization not in use

---

rl_coach/dashboard.py

fix dashboard to allow connections from a remote machine.

---

README.md

update CARLA install docs to note python client.

---

rl_coach/agents/agent.py
rl_coach/agents/categorical_dqn_agent.py
rl_coach/agents/nec_agent.py
rl_coach/agents/value_optimization_agent.py
rl_coach/environments/gym_environment.py
rl_coach/presets/CartPole_DQN_BatchRL.py
rl_coach/tests/presets/test_presets.py
rl_coach/tests/test_golden.py
rl_coach/utils.py

integration test changes to override heatup to 1000 steps +  run each preset for 30 sec (to make sure we reach the train part)

integration test changes to reach the train part

---

rl_coach/tests/conftest.py
rl_coach/tests/test_checkpoint.py
rl_coach/tests/test_coach_args.py
rl_coach/tests/utils/args_utils.py
rl_coach/tests/utils/definitions.py
rl_coach/tests/utils/presets_utils.py
rl_coach/tests/utils/test_utils.py

*new tests:
- test_preset_n_and_ew
- test_preset_n_and_ew_and_onnx
* code utils improvements (all utils)
* improve checkpoint_test
* new functionality for functional_test markers and presets lists

tests: added new tests

---

.circleci/config.yml
docker/Makefile
rl_coach/presets/Mujoco_A3C_LSTM.py

- fix multi environment vairables in configci
- removing bitflip from mujoco tests
- add bitflip to gym

tests: fix multi environment variables in configci

---

rl_coach/tests/test_checkpoint.py
rl_coach/tests/utils/args_utils.py
rl_coach/tests/utils/test_utils.py

new test added:
- test_restore_checkpoint[tensorflow, mxnet]
fix failed tests in CI
improve utils

tests: new checkpoint mxnet test + fix utils

---

.gitignore
rl_coach/agents/agent.py
rl_coach/agents/agent_interface.py
rl_coach/base_parameters.py
rl_coach/core_types.py
rl_coach/level_manager.py
rl_coach/rollout_worker.py
rl_coach/tests/test_core_types.py

Some minor re factoring and cleanup as I get ready for eRL implementation

Minor re-factoring

---

rl_coach/tests/test_checkpoint.py
rl_coach/tests/utils/args_utils.py

- fixed: failure issue from nightly 
- fixed: mxnet preset for checkpoint restore

tests: minor fix for functional tests

---

rl_coach/architectures/tensorflow_components/heads/__init__.py

Include missing RegressionHead. 

---

rl_coach/tests/conftest.py
rl_coach/tests/test_checkpoint.py
rl_coach/tests/utils/args_utils.py
rl_coach/tests/utils/test_utils.py

* fixed get_csv_files function
- fixed seed test
* fixed clres on conftest - now can modify paths during test run
- fixed the mxnet checkpoint test

tests: fixed failed tests - stabling CI

---

rl_coach/architectures/tensorflow_components/embedders/embedder.py

Printing input size as part of network summary

---

rl_coach/filters/observation/observation_rescale_size_by_factor_filter.py
rl_coach/filters/observation/observation_rescale_to_size_filter.py
rl_coach/tests/filters/observation/test_observation_rescale_size_by_factor_filter.py
rl_coach/tests/filters/observation/test_observation_rescale_to_size_filter.py
rl_coach/tests/filters/test_filters_stacking.py

Replacing scipy.misc.resize as it was removed in scipy 1.3.0.

moving to skimage.transform.resize

---

requirements.txt

fixed issue https://github.com/NervanaSystems/coach/issues/324

Removed unnecessary futures dependency

---

rl_coach/agents/ddpg_agent.py
rl_coach/architectures/head_parameters.py
rl_coach/architectures/tensorflow_components/heads/__init__.py
rl_coach/architectures/tensorflow_components/heads/ddpg_v_head.py

A bug fix for DDPG, where the update to the policy network was based on the sum of the critic's Q predictions on the batch instead of their mean.

DDPG Critic Head Bug Fix

---

tutorials/0. Quick Start Guide.ipynb
tutorials/Resources/exploration.py

Adding a few command line examples per users request.

Additional cmd line examples

---

.circleci/config.yml
CONTRIBUTING.md
README.md
rl_coach/tests/pytest.ini
setup.py

Updating README.
Shortening nightly test cycle.

Release 1.0.0

---

requirements.txt

Updating pillow version as there's a potential security risk with version < 6.2.0

Update Pillow Version

---

rl_coach/agents/acer_agent.py
rl_coach/agents/actor_critic_agent.py
rl_coach/agents/agent_interface.py
rl_coach/agents/bc_agent.py
rl_coach/agents/bootstrapped_dqn_agent.py
rl_coach/agents/categorical_dqn_agent.py
rl_coach/agents/clipped_ppo_agent.py
rl_coach/agents/ddpg_agent.py
rl_coach/agents/dfp_agent.py
rl_coach/agents/dqn_agent.py
rl_coach/agents/imitation_agent.py
rl_coach/agents/mmc_agent.py
rl_coach/agents/n_step_q_agent.py
rl_coach/agents/naf_agent.py
rl_coach/agents/nec_agent.py
rl_coach/agents/pal_agent.py
rl_coach/agents/policy_gradients_agent.py
rl_coach/agents/ppo_agent.py
rl_coach/agents/qr_dqn_agent.py
rl_coach/agents/soft_actor_critic_agent.py
rl_coach/agents/td3_agent.py

Cherry picking from #478 to ease diff/merge

Add is_on_policy property to agents

---

rl_coach/agents/agent.py
rl_coach/coach.py
rl_coach/data_stores/nfs_data_store.py
rl_coach/data_stores/s3_data_store.py
rl_coach/logger.py
rl_coach/memories/backend/redis.py
rl_coach/orchestrators/kubernetes_orchestrator.py
rl_coach/utils.py

Cherry picking from #478 to ease merge

Logging screen output to file

---

rl_coach/architectures/embedder_parameters.py
rl_coach/architectures/layers.py
rl_coach/architectures/tensorflow_components/embedders/embedder.py
rl_coach/architectures/tensorflow_components/embedders/image_embedder.py
rl_coach/architectures/tensorflow_components/embedders/tensor_embedder.py
rl_coach/architectures/tensorflow_components/embedders/vector_embedder.py
rl_coach/architectures/tensorflow_components/layers.py

Add Flatten layer to architectures + make flatten optional in embedders
